#localstorage - mongo-pvc
#what do we want?


apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
spec:
  storageClassName: mylocalstorage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
# How do we want it.
apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-storage
spec:
  storageClassName: mylocalstorage
  capacity:
    storage: 1Gi
  accessModes:
      - ReadWriteOnce
  hostPath:
    path: "/mnt/some/newdirectory/structure"
    type: DirectoryOrCreate
